version: '3.3'
services:
  webserver:
    ports:
      - 80:80
    image: webserver:latest
    volumes:
            - /var/lib/jenkins/workspace/final_project:/usr/share/nginx/html/
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./log/nginx/jenkins:/var/log/nginx/jenkins/
